title: 'O|eks L:tus'
description: "O|eks L:tus"
url: https://oreksu.com

header_pages:
  - pages/index.md
  - pages/delta.md
  - pages/lambda.md
  - pages/research.md
  - pages/setup.md
  - pages/links.md
  - pages/contact.md

style: dark
listen_for_clients_preferred_style: true

footer: I am orreksu

markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
